name: Documentation

on:
  push:
    branches: [rolling]
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq python3-sphinx
          cd ./doc/sphinx/
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          cd ./doc/sphinx/
          source .venv/bin/activate
          make html
          cd ../..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/sphinx/build/html
          force_orphan: true

